import { AppLoads } from './utils.d';

export const AppList: {
  [key: string]: { name: string; ctx: string; load: AppLoads };
} = {
  books: { name: 'Books', ctx: 'books', load: 'None' },
  booth: { name: 'Photo Booth', ctx: 'booth', load: 'None' },
  calculator: { name: 'Calculator', ctx: 'calculator', load: 'None' },
  calendar: { name: 'Calendar', ctx: 'calendar', load: 'None' },
  compressor: { name: 'Compressor', ctx: 'compressor', load: 'None' },
  contacts: { name: 'Contacts', ctx: 'contacts', load: 'Contacts' },
  cut: { name: 'Cut the Rope', ctx: 'cut', load: 'None' },
  dictionary: { name: 'Dictionary', ctx: 'dictionary', load: 'None' },
  excel: { name: 'Microsoft Excel', ctx: 'excel', load: 'None' },
  facetime: { name: 'Facetime', ctx: 'facetime', load: 'None' },
  final: { name: 'Final Cut Pro X', ctx: 'final', load: 'None' },
  find: { name: 'Find My', ctx: 'find', load: 'None' },
  finder: { name: 'Finder', ctx: 'finder', load: 'Finder' },
  gara: { name: 'Garage Band', ctx: 'garageband', load: 'None' },
  github: { name: 'Github Desktop', ctx: 'github', load: 'None' },
  home: { name: 'Home', ctx: 'home', load: 'None' },
  keynote: { name: 'Keynote', ctx: 'keynote', load: 'None' },
  launchpad: { name: 'Launchpad', ctx: 'launchpad', load: 'Launchpad' },
  logic: { name: 'Logic Pro', ctx: 'logic', load: 'None' },
  mail: { name: 'Mail', ctx: 'mail', load: 'Mail' },
  maps: { name: 'Maps', ctx: 'maps', load: 'Maps' },
  monitor: { name: 'Monitor', ctx: 'monitor', load: 'None' },
  music: { name: 'Music', ctx: 'music', load: 'Music' },
  news: { name: 'News', ctx: 'news', load: 'None' },
  notes: { name: 'Notes', ctx: 'notes', load: 'Notes' },
  numbers: { name: 'Numbers', ctx: 'numbers', load: 'None' },
  onenote: { name: 'Microsoft OneNote', ctx: 'onenote', load: 'None' },
  outlook: { name: 'Microsoft Outlook', ctx: 'outlook', load: 'None' },
  pages: { name: 'Pages', ctx: 'pages', load: 'None' },
  photos: { name: 'Photos', ctx: 'photos', load: 'Photos' },
  podcasts: { name: 'Podcasts', ctx: 'podcasts', load: 'None' },
  powerpoint: {
    name: 'Microsoft PowerPoint',
    ctx: 'powerpoint',
    load: 'None',
  },
  preferences: {
    name: 'System Preferences',
    ctx: 'preferences',
    load: 'Preferences',
  },
  preview: { name: 'Preview', ctx: 'preview', load: 'None' },
  reminders: { name: 'Reminders', ctx: 'reminders', load: 'Reminders' },
  safari: { name: 'Sarafi', ctx: 'safari', load: 'Safari' },
  screenshot: { name: 'Screenshot', ctx: 'screenshot', load: 'None' },
  siri: { name: 'Siri', ctx: 'siri', load: 'Siri' },
  stickies: { name: 'Stickies', ctx: 'stickies', load: 'None' },
  store: { name: 'App Store', ctx: 'store', load: 'None' },
  swift: { name: 'Swift Playground', ctx: 'swift', load: 'None' },
  terminal: { name: 'Terminal', ctx: 'terminal', load: 'None' },
  textedit: { name: 'TextEdit', ctx: 'textedit', load: 'None' },
  time: { name: 'Time Machine', ctx: 'time', load: 'None' },
  vscode: { name: 'Visual Studio Code', ctx: 'vscode', load: 'None' },
  wechat: { name: 'WeChat', ctx: 'wechat', load: 'None' },
  word: { name: 'Microsoft Word', ctx: 'word', load: 'None' },
  xcode: { name: 'Xcode', ctx: 'xcode', load: 'None' },
};
