import { AppStateAction } from './utils.d';

export const AppList: {
  [key: string]: { name: string; ctx: string; action: AppStateAction };
} = {
  books: { name: 'Books', ctx: 'books', action: 'NONE' },
  booth: { name: 'Photo Booth', ctx: 'booth', action: 'NONE' },
  calculator: { name: 'Calculator', ctx: 'calculator', action: 'NONE' },
  calendar: { name: 'Calendar', ctx: 'calendar', action: 'NONE' },
  compressor: { name: 'Compressor', ctx: 'compressor', action: 'NONE' },
  contacts: { name: 'Contacts', ctx: 'contacts', action: 'CONTACTS_OPENED' },
  cut: { name: 'Cut the Rope', ctx: 'cut', action: 'NONE' },
  dictionary: { name: 'Dictionary', ctx: 'dictionary', action: 'NONE' },
  excel: { name: 'Microsoft Excel', ctx: 'excel', action: 'NONE' },
  facetime: { name: 'Facetime', ctx: 'facetime', action: 'NONE' },
  final: { name: 'Final Cut Pro X', ctx: 'final', action: 'NONE' },
  find: { name: 'Find My', ctx: 'find', action: 'NONE' },
  finder: { name: 'Finder', ctx: 'finder', action: 'FINDER_OPENED' },
  gara: { name: 'Garage Band', ctx: 'garageband', action: 'NONE' },
  github: { name: 'Github Desktop', ctx: 'github', action: 'NONE' },
  home: { name: 'Home', ctx: 'home', action: 'NONE' },
  keynote: { name: 'Keynote', ctx: 'keynote', action: 'NONE' },
  launchpad: {
    name: 'Launchpad',
    ctx: 'launchpad',
    action: 'LAUNCHPAD_OPENED',
  },
  logic: { name: 'Logic Pro', ctx: 'logic', action: 'NONE' },
  mail: { name: 'Mail', ctx: 'mail', action: 'MAIL_OPENED' },
  maps: { name: 'Maps', ctx: 'maps', action: 'MAPS_OPENED' },
  monitor: { name: 'Monitor', ctx: 'monitor', action: 'NONE' },
  music: { name: 'Music', ctx: 'music', action: 'MUSIC_OPENED' },
  news: { name: 'News', ctx: 'news', action: 'NONE' },
  notes: { name: 'Notes', ctx: 'notes', action: 'NOTES_OPENED' },
  numbers: { name: 'Numbers', ctx: 'numbers', action: 'NONE' },
  onenote: { name: 'Microsoft OneNote', ctx: 'onenote', action: 'NONE' },
  outlook: { name: 'Microsoft Outlook', ctx: 'outlook', action: 'NONE' },
  pages: { name: 'Pages', ctx: 'pages', action: 'NONE' },
  photos: { name: 'Photos', ctx: 'photos', action: 'PHOTOS_OPENED' },
  podcasts: { name: 'Podcasts', ctx: 'podcasts', action: 'NONE' },
  powerpoint: {
    name: 'Microsoft PowerPoint',
    ctx: 'powerpoint',
    action: 'NONE',
  },
  preferences: {
    name: 'System Preferences',
    ctx: 'preferences',
    action: 'PREFERENCES_OPENED',
  },
  preview: { name: 'Preview', ctx: 'preview', action: 'NONE' },
  reminders: {
    name: 'Reminders',
    ctx: 'reminders',
    action: 'REMINDERS_OPENED',
  },
  safari: { name: 'Sarafi', ctx: 'safari', action: 'SAFARI_OPENED' },
  screenshot: { name: 'Screenshot', ctx: 'screenshot', action: 'NONE' },
  siri: { name: 'Siri', ctx: 'siri', action: 'SIRI_OPENED' },
  stickies: { name: 'Stickies', ctx: 'stickies', action: 'NONE' },
  store: { name: 'App Store', ctx: 'store', action: 'NONE' },
  swift: { name: 'Swift Playground', ctx: 'swift', action: 'NONE' },
  terminal: { name: 'Terminal', ctx: 'terminal', action: 'NONE' },
  textedit: { name: 'TextEdit', ctx: 'textedit', action: 'NONE' },
  time: { name: 'Time Machine', ctx: 'time', action: 'NONE' },
  vscode: { name: 'Visual Studio Code', ctx: 'vscode', action: 'NONE' },
  wechat: { name: 'WeChat', ctx: 'wechat', action: 'NONE' },
  word: { name: 'Microsoft Word', ctx: 'word', action: 'NONE' },
  xcode: { name: 'Xcode', ctx: 'xcode', action: 'NONE' },
};
